schema_version = "1.0.0"

id = "custombackupfolder"
version = "0.1.1"
name = "Custom Backup Folder"
type = "add-on"
tagline = "A few additional tools for better Save Version management"
blender_version_min = "4.2.0"
tags = ["System"]
maintainer = "Celdor"
website = "https://projects.blender.org/FrankWE/custombackupfolder.git"
license = ["SPDX:GPL-3.0-or-later"]

